app:
  host: 0.0.0.0
  port: 8080

templates:
  dir : templates
  index : index.html

input_image_path: images\inputImage.jpg

pred_stages_val: 2

results_path : results\croppedImage.jpg

exported_model_path : datasets\experiment_ssd\2018_07_25_14-00\exported_model\frozen_inference_graph.pb

labels_file: datasets\records\classes.pbtxt

num_classes : 37

min_confidence : 0.5